#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPlugins.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BackEndToolType
	{
		
		/// <summary>
		/// ConnectorAction
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ConnectorAction", 1, null, "ConnectorAction")]
		Connectoraction = 1,
		
		/// <summary>
		/// DataverseCustomAPI
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DataverseCustomAPI", 0, null, "DataverseCustomAPI")]
		Dataversecustomapi = 0,
		
		/// <summary>
		/// Graph
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Graph", 2, null, "Graph")]
		Graph = 2,
		
		/// <summary>
		/// RemoteAPI
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RemoteAPI", 4, null, "RemoteAPI")]
		Remoteapi = 4,
		
		/// <summary>
		/// RemoteMCP
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RemoteMCP", 3, null, "RemoteMCP")]
		Remotemcp = 3,
		
		/// <summary>
		/// SdkMessagePair
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SdkMessagePair", 5, null, "SdkMessagePair")]
		Sdkmessagepair = 5,
	}
}
#pragma warning restore CS1591
