#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPlugins.Entities
{
	
	
	/// <summary>
	/// Type of channel activities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ConvertRule_ChannelActivity
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Appointment", 2)]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer Voice alert", 9)]
		CustomerVoiceAlert = 10639,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer Voice survey invite", 10)]
		CustomerVoiceSurveyInvite = 10640,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer Voice survey response", 11)]
		CustomerVoiceSurveyResponse = 10641,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Donation", 8)]
		Donation = 10420,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 1)]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Invite Redemption", 6)]
		InviteRedemption = 10262,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Phone Call", 0)]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Portal Comment", 7)]
		PortalComment = 10263,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Social Activity", 4)]
		SocialActivity = 4216,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Task", 3)]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Teams chat", 5)]
		TeamsChat = 10121,
	}
}
#pragma warning restore CS1591
