#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPlugins.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum HttpMethod
	{
		
		/// <summary>
		/// DELETE Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DELETE", 4, null, "DELETE Method")]
		Delete = 4,
		
		/// <summary>
		/// GET Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GET", 0, null, "GET Method")]
		Get = 0,
		
		/// <summary>
		/// PATCH Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PATCH", 3, null, "PATCH Method")]
		Patch = 3,
		
		/// <summary>
		/// POST Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("POST", 1, null, "POST Method")]
		Post = 1,
		
		/// <summary>
		/// PUT Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PUT", 2, null, "PUT Method")]
		Put = 2,
	}
}
#pragma warning restore CS1591
