#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPlugins.Entities
{
	
	
	/// <summary>
	/// List of Mobile Offline Enabled Entities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MobileOfflineEnabledEntities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Account", 0)]
		Account = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Activity File Attachment", 12)]
		ActivityFileAttachment = 10120,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Appointment", 8)]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Approval Stage Approval", 23)]
		ApprovalStageApproval = 10681,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Approval Stage Condition", 24)]
		ApprovalStageCondition = 10682,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Approval Stage Order", 25)]
		ApprovalStageOrder = 10683,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Attachment", 5)]
		Attachment = 1001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Challenge Management Process", 19)]
		ChallengeManagementProcess = 10423,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Contact", 1)]
		Contact = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 9)]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Idea to Project Business Process", 18)]
		IdeaToProjectBusinessProcess = 10421,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Image Descriptor", 17)]
		ImageDescriptor = 1007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Interim Update Knowledge Article", 47)]
		InterimUpdateKnowledgeArticle = 10751,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Knowledge Article Attachment", 14)]
		KnowledgeArticleAttachment = 10135,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Knowledge Article Custom Entity", 48)]
		KnowledgeArticleCustomEntity = 10756,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Knowledge Article Image", 13)]
		KnowledgeArticleImage = 10129,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Knowledge Harvest Job Record", 22)]
		KnowledgeHarvestJobRecord = 10636,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("msdyn_historicalcaseharvestbatch", 20)]
		MsdynHistoricalcaseharvestbatch = 10634,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("msdyn_historicalcaseharvestrun", 21)]
		MsdynHistoricalcaseharvestrun = 10635,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Note", 2)]
		Note = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OrganizationDataSyncFnoState", 15)]
		Organizationdatasyncfnostate = 10154,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OrganizationDataSyncState", 16)]
		Organizationdatasyncstate = 10155,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PowerPagesDDOSAlert", 26)]
		Powerpagesddosalert = 10653,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue", 6)]
		Queue = 2020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue Item", 7)]
		QueueItem = 2029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 003d6e0323", 30)]
		ReserveEntity003D6e0323 = 10713,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 19ae473ee0", 35)]
		ReserveEntity19Ae473ee0 = 10719,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 3b6b79adbe", 41)]
		ReserveEntity3B6b79adbe = 10725,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 3b75119e62", 33)]
		ReserveEntity3B75119e62 = 10717,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 3dd29e4cd0", 46)]
		ReserveEntity3Dd29e4cd0 = 10733,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 3f1a2c36ea", 29)]
		ReserveEntity3F1a2c36ea = 10710,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 47023620fb", 42)]
		ReserveEntity47023620Fb = 10729,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 53086a51de", 39)]
		ReserveEntity53086A51de = 10723,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 57659d43c5", 40)]
		ReserveEntity57659D43c5 = 10724,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 634aefeeb1", 38)]
		ReserveEntity634Aefeeb1 = 10722,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 69f4780336", 34)]
		ReserveEntity69F4780336 = 10718,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 6d8ea028e4", 37)]
		ReserveEntity6D8ea028e4 = 10721,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 8d7dc98642", 43)]
		ReserveEntity8D7dc98642 = 10730,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 97b4f39bad", 28)]
		ReserveEntity97B4f39bad = 10709,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity a625e9c710", 32)]
		ReserveEntityA625e9c710 = 10716,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity cb3a31c8bf", 27)]
		ReserveEntityCb3a31c8bf = 10708,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity e470aed1ad", 45)]
		ReserveEntityE470aed1ad = 10732,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity f3c18a5e9f", 44)]
		ReserveEntityF3c18a5e9f = 10731,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity f6b71c8738", 36)]
		ReserveEntityF6b71c8738 = 10720,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity f9fe7a6cb7", 31)]
		ReserveEntityF9fe7a6cb7 = 10715,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity fd028755a2", 49)]
		ReserveEntityFd028755a2 = 10763,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sales Process", 50)]
		SalesProcess = 10764,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sales Process 2", 51)]
		SalesProcess2 = 10765,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SLA KPI Instance", 11)]
		SlaKpiInstance = 9752,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Task", 10)]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Team", 4)]
		Team = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("User", 3)]
		User = 8,
	}
}
#pragma warning restore CS1591
