#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPlugins.Entities
{
	
	
	/// <summary>
	/// AI Model Task Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_AIModelTaskType
	{
		
		/// <summary>
		/// Classification
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Classification", 2, "#0000ff", "Classification")]
		Classification = 100000002,
		
		/// <summary>
		/// None
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("None", 0, "#0000aa", "None")]
		None = 100000000,
		
		/// <summary>
		/// QueryBoosting
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("QueryBoosting", 1, "#0000cc", "QueryBoosting")]
		Queryboosting = 100000001,
	}
}
#pragma warning restore CS1591
