#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPlugins.Entities
{
	
	
	/// <summary>
	/// Types of reports.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum OptionSet_RunReport
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("All applicable records", 0)]
		AllApplicableRecords = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("All records on all pages in current view", 2)]
		AllRecordsOnAllPagesInCurrentView = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("The selected records", 1)]
		TheSelectedRecords = 0,
	}
}
#pragma warning restore CS1591
