#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPlugins.Entities
{
	
	
	/// <summary>
	/// Power Pages Site Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PowerPageSiteType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Code Site", 1, "#0000ff")]
		CodeSite = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Default", 0, "#0000ff")]
		Default = 0,
	}
}
#pragma warning restore CS1591
