#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPlugins.Entities
{
	
	
	/// <summary>
	/// Power Pages Source File Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PowerPagesSourceFileType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CSS", 2, "#0000ff")]
		Css = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Html", 0, "#0000ff")]
		Html = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Java script", 1, "#0000ff")]
		JavaScript = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("JSON", 5, "#0000ff")]
		Json = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("TSX", 3, "#0000ff")]
		Tsx = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web Template", 7, "#0000ff")]
		WebTemplate = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("XML", 4, "#0000ff")]
		Xml = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Yml", 6, "#0000ff")]
		Yml = 7,
	}
}
#pragma warning restore CS1591
