#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPlugins.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ServerType
	{
		
		/// <summary>
		/// Server for Agent 365
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent365", 0, null, "Server for Agent 365")]
		Agent365 = 0,
	}
}
#pragma warning restore CS1591
